export const AUTH_START="AUTH_START";
export const AUTH_SUCCESS="AUTH_SUCCESS";
export const AUTH_FAIL="AUTH_FAIL";
export const LOGIN_SUCCESS ="LOGIN_SUCCESS";
export const AUTH_LOGOUT="AUTH_LOGOUT";
export const CONTACT="CONTACT";
export const REDIRECTPATH='REDIRECTPATH';
